name: tests

on: [push, pull_request]

env:
  build_dir: "build"
  build_type: "Release"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ g++, clang++ ]
    steps:
      - uses: actions/checkout@v3
      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-program-options-dev
      - name: Install Google Test
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib
      - name: Build
        run: make

      - name: Test
        run: ./run_tests
